name: portafolio_new_fl
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_loading_border: ^0.0.2
  animated_text_kit: ^4.2.3
  animated_toggle_switch: ^0.8.4
  animations: ^2.0.11
  cloud_firestore: ^5.6.4
  confetti: ^0.8.0
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.5.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^3.0.0 
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  intl_phone_number_input: ^0.7.4
  libphonenumber_web: ^0.3.2
  lucide_icons_flutter: ^1.2.7
  mouse_parallax: ^1.1.0
  provider: ^6.1.2
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/desing/
    - assets/img/icons/
    - assets/img/photos/
    - assets/videos/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
